version: '3.8'

services:
  calculator-api:
    build:
      context: .
      dockerfile: AntlrCalculator.Api/Dockerfile
    container_name: calculator-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - calculator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  calculator-network:
    name: calculator-network
    driver: bridge 